sudo: required # For apt-get install python3
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
  matrix:
    # - ANDROID_TARGET=android-16
    - ANDROID_TARGET=android-19
    # - ANDROID_TARGET=android-22
    # - ANDROID_TARGET=android-25

os: linux
language: android
jdk: oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml` (https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - tools # to install Android SDK tools 25.2.x (https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943). The before-test.sh script will update to the latest tools using sdkmanager
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env: CI_IOS_TESTS=true J2OBJC_VERSION=1.3.1 J2OBJC_HOME=/tmp/j2objc-$J2OBJC_VERSION
    - os: linux
      sudo: false
      language: java
      jdk: oraclejdk8
      env: CI_CODE_GENERATOR_TESTS=true

before_script:
    - ./scripts/before-test.sh
script:
    - ./scripts/run-tests.sh
